# Generated by Django 5.2.4 on 2025-11-01 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_migrate_transportrequest_to_pool'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transportpool',
            options={'ordering': ['-date', '-created_at']},
        ),
        migrations.RemoveField(
            model_name='transportpool',
            name='price_per_km',
        ),
        migrations.AddField(
            model_name='pooljoinrequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='transportpool',
            name='distance_km',
            field=models.FloatField(blank=True, help_text='Optional distance in kilometers', null=True),
        ),
        migrations.AddField(
            model_name='transportpool',
            name='price_per_kg',
            field=models.FloatField(default=0.0, help_text='Computed price per kg for route'),
        ),
        migrations.AddField(
            model_name='transportpool',
            name='rate_per_kg_per_km',
            field=models.FloatField(default=1.0, help_text='System rate per kg per km (derived)'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='display_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='license_plate',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pooljoinrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('FULL', 'Full')], default='PENDING', max_length=10),
        ),
        migrations.AlterField(
            model_name='transportpool',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('FULL', 'Full')], default='PENDING', max_length=10),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='route',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.CharField(choices=[('Truck', 'Truck'), ('Tractor', 'Tractor'), ('Pickup', 'Pickup'), ('Other', 'Other')], max_length=50),
        ),
    ]
