# Generated by Django 5.2.4 on 2025-11-01 21:01

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_transportpool_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportpool',
            name='price_per_km',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
