# Generated by Django 5.2.4 on 2025-11-01 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_transportpool_price_per_km'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportpool',
            name='provider_load',
            field=models.FloatField(default=0.0, help_text='Provider load in kg included in this pool'),
        ),
        migrations.AddField(
            model_name='transportpool',
            name='provider_share',
            field=models.FloatField(default=0.0, help_text='Provider cost share based on provider_load ratio'),
        ),
        migrations.AddField(
            model_name='transportpool',
            name='rate_per_km',
            field=models.FloatField(default=0.0, help_text='Vehicle rate per km based on vehicle type'),
        ),
        migrations.AddField(
            model_name='transportpool',
            name='total_cost',
            field=models.FloatField(default=0.0, help_text='Total trip cost = distance_km * rate_per_km'),
        ),
        migrations.AlterField(
            model_name='transportpool',
            name='price_per_kg',
            field=models.FloatField(default=0.0, help_text='[Deprecated] Computed price per kg for route'),
        ),
        migrations.AlterField(
            model_name='transportpool',
            name='rate_per_kg_per_km',
            field=models.FloatField(default=1.0, help_text='[Deprecated] Rate per kg per km'),
        ),
    ]
