# Generated by Django 5.2.4 on 2025-11-02 21:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_transportpool_completed_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(blank=True, max_length=120)),
                ('contact', models.CharField(blank=True, max_length=20)),
                ('farm_size', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('preferred_crops', models.JSONField(blank=True, default=list)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='farmerprofile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
